### ISSUE TITLE
Notifications showing 10 no matter what

### ISSUE THREAD

**Issue by eliasmurcray** [eliasmurcray/ka-notifications#17]
This was reported by Lemon, xacer, and I am experiencing it as well. Moving to top of the importance list.

**Comment by Reginald-Gillespie** [comment]
Fyi for debugging, I do not have this issue.

**Comment by eliasmurcray** [comment]
@gaminglemonss Can you send in the JSON resulting from "Inspect Popup"? I would like to see what you are working with.

**Comment by Reginald-Gillespie** [comment]
I just got one notification, but it showed that I have two (and this account has a total of two notifications). Make of that what you will.

**Comment by astro-develops** [comment]
*Note: Even without using the extension, I get a notification dot on my profile with no real notifications. 

I'd probably assume this is just a KA bug with their side of the system and not an issue with the extension.
