### ISSUE TITLE
You must be logged in to use this extension.

### ISSUE THREAD

**Issue by ccaven** [eliasmurcray/ka-notifications#2]

**Comment by Reginald-Gillespie** [comment]
This is a known issue, the API was updated the other day. iirc the update should be approved by google or whatever tomorrow.

**Comment by ccaven** [comment]
I figured. I had a draft issue open and was looking for more details, and apparently GitHub decided it wanted the issue posted lol

**Comment by ccaven** [comment]
Actually might as well keep it open until it's fixed :octocat:

**Comment by eliasmurcray** [comment]
Leaving an update here: Google Testers have rejected the previous submission due to privacy policy requirements, which the extension ultimately did not need. Another submission has been created.

**Comment by eliasmurcray** [comment]
Chrome version has been updated. Resolving this issue.
