### ISSUE TITLE
[Question] Exclamation Mark Notifications?

### ISSUE THREAD

**Issue by 99TheDark** [eliasmurcray/ka-notifications#20]
What does this even mean?

<img width="37" alt="Screenshot 2023-04-24 at 7 58 55 AM" src="https://user-images.githubusercontent.com/104472362/234036181-bd173dde-52ed-4663-b612-9d04cfe3af46.png">

**Comment by eliasmurcray** [comment]
Hello, `getNotificationsForUser` query has been updated. The fix will be published shortly. Not sure why it didn't throw an error.

**Comment by 99TheDark** [comment]
It also never loads. I'll just wait for now.

**Comment by eliasmurcray** [comment]
The update is released

**Comment by 99TheDark** [comment]
Same thing. Is there a way to check if my version has been updated?

**Comment by Reginald-Gillespie** [comment]
go to `chrome://extensions/?id=gdlfnahbohjggjhpcmabnfikiigncjbd`, version number is there.
Can confirm I also have the same problem.

**Comment by eliasmurcray** [comment]
Anything on inspect?

**Comment by Reginald-Gillespie** [comment]
No, just saying issue is for everyone. I just applied the update (process is not automatic for me with ungoogled chromium)

**Comment by 99TheDark** [comment]
1.3.10 for me.

**Comment by 99TheDark** [comment]
`failed to load resource: the server responded with a status of 403 ()`

Weird, not finding a script.

**Comment by eliasmurcray** [comment]
It should be 1.3.11 btw

**Comment by 99TheDark** [comment]
Is there any way to force an update, or should I just sit and wait until it becomes 1.3.11? Also, @Reginald-Gillespie, what version are you on?

**Comment by eliasmurcray** [comment]
You can always force an update by going to chrome://extensions and clicking Update in the top left.

**Comment by 99TheDark** [comment]
All fixed 👍

**Comment by Reginald-Gillespie** [comment]
@99TheDark when I relaunch it'll be on .11.

**Comment by 99TheDark** [comment]
Alright. It may be fixed now then.

**Comment by 99TheDark** [comment]
And— it stopped working.

**Comment by 99TheDark** [comment]
`ROR [getNotificationsForUser]:  Error in GraphQL getNotificationsForUser call: Server responded  with status 403 and body "routes._validatePermission: [unauthorized error] Operation not found in safelist, hash = …, operation = getNotificationsForUser"`

**Comment by eliasmurcray** [comment]
I do not have this error, is there any more info you can give for this?

**Comment by eliasmurcray** [comment]
Is it in the background script

**Comment by 99TheDark** [comment]
I just opened the error log. By just reading it it's probably a permissions error in GraphQL.

**Comment by 99TheDark** [comment]
I got like 100 of them, prob one for each notification. Not sure tho, just a guess.

**Comment by Reginald-Gillespie** [comment]
Try logging out of KA then back in and see if it still has the error?

**Comment by eliasmurcray** [comment]
Yes, try doing what WKoA said. I am not having this issue

**Comment by 99TheDark** [comment]
Nope.

**Comment by astro-develops** [comment]
@99TheDark 
I don't seem to have this issue either. Seems like something on your end.

**Comment by 99TheDark** [comment]
Weird. I'll try deleting in and reinstalling it maybe.

**Comment by 99TheDark** [comment]
It seemed to have fixed it.
