### ISSUE TITLE
Light mode code snippets

### ISSUE THREAD

**Issue by 99TheDark** [eliasmurcray/ka-notifications#5]
In Dark mode, the  code looks pretty good, though the container could be more distinct. However, in light mode, there is still a black box, which looks really strange.

<img width="454" alt="Screenshot 2023-03-10 at 5 29 29 PM" src="https://user-images.githubusercontent.com/104472362/224457487-efc32c9e-7eff-45e5-b144-b4eefb55ee60.png">

**Comment by eliasmurcray** [comment]
I will update this within 48 hours! Thanks for letting me know.

**Comment by 99TheDark** [comment]
Sounds good :)

**Comment by eliasmurcray** [comment]
Light code theme has been added! The update will be deployed to production in less than 12 hours, following verification.

**Comment by 99TheDark** [comment]
Yay, it looks all nice now, with the text fix too :D
