### ISSUE TITLE
[Feature Request] Clickable Users

### ISSUE THREAD

**Issue by 99TheDark** [eliasmurcray/ka-notifications#7]
Though a small feature, it might be nice to be able to click on someone's avatar or username (a username might be accidentally clicked, but both work) and go straight to their profile. I assume you already have their KAID within the message history as well.

**Comment by eliasmurcray** [comment]
I think this would be a great idea, but as it stands the sender's KAID is not included in the Notification Response. This would cause a need for a separate API request. This may be implemented in the future, just not now as we work on performance improvements for the extension.

**Comment by 99TheDark** [comment]
Alright.

**Comment by eliasmurcray** [comment]
I don't think we will implement this feature unless the KA API changes. After considering the different variations of notifications, the added complexity if we were to add this is too high for the extension.
