### ISSUE TITLE
Extension Error in background.js

### ISSUE THREAD

**Issue by eliasmurcray** [eliasmurcray/ka-notifications#8]
After a certain amount of time this error occurs in the background script.

```
Error code 2: Error in GraphQL getNotificationsForUser call: Server responded  with status 403 and body "routes._validatePermission: [unauthorized error] Operation not found in safelist, hash = 414885102, operation = getNotificationsForUser"
```

**Comment by Reginald-Gillespie** [comment]
Why would this happen? Do you have multiple payloads for `getNotificationsForUser` and one of them is old? Another thing that seems possible but not likely is that the KAAS expired, but I don't think that's the error it would give in that case.

**Comment by eliasmurcray** [comment]
The endpoint has been updated for the query. I have updated it, but it seems the handler may need to be updated as well.

**Comment by eliasmurcray** [comment]
The handler has been updated and the update will be released within 2 hours. Closing as resolved.
