### ISSUE TITLE
[Question] Caching notifications

### ISSUE THREAD

**Issue by 99TheDark** [eliasmurcray/ka-notifications#9]
Do you do this, and is this even possible? It would greatly decerease loading time when opening & closing again, it's kind of annoying to wait even after a little time. Like 25 message buffer would be nice to have.

**Comment by Reginald-Gillespie** [comment]
He does cache them sometimes, but I do agree that it could be improved. Like I would like it to auto-fetch update after opening up with cache possibly, and maybe a larger buffer like you said would be good.

**Comment by eliasmurcray** [comment]
The notifications are cached every minute, only right before the notification count is updated, otherwise the cache is the same. This way it is optimized to not slow down the main thread.
